apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-ncxk
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-oioz-tenant/rhtap-demo-app/hacbs-test-project-ncxk@sha256:5ea1eebfe79d4def113cc5ff9d10b25b37d148799608bc2806ce49b6c3571e88
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
