apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-ncxk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-ncxk
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-ncxk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-ncxk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-ncxk
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-oioz-tenant/rhtap-demo-app/hacbs-test-project-ncxk@sha256:5ea1eebfe79d4def113cc5ff9d10b25b37d148799608bc2806ce49b6c3571e88
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
